---
# Small 3D U-Net (Proposal)
exp_001: &exp_001
  combine_probabilities: true
  dataset_root: ../dataset
  dataset_size_code: highres3d
  dataset_type: 3d
  epochs: 500
  iter_per_epoch: 10
  learning_rate: 0.0001
  model_id: unet_3d_proposal
  weight_decay: 1.0e-06

exp_002:
  <<: *exp_001
exp_003:
  <<: *exp_001

# Small Residual 3D U-Net
exp_004: &exp_004
  combine_probabilities: true
  dataset_root: ../dataset
  dataset_size_code: highres3d
  dataset_type: 3d
  epochs: 500
  iter_per_epoch: 10
  learning_rate: 0.0001
  model_id: unet_3d_residual_proposal
  weight_decay: 1.0e-05

exp_005:
  <<: *exp_004

exp_006:
  <<: *exp_004

# Deepmind's model
exp_007: &exp_007
  combine_probabilities: true
  dataset_root: ../dataset
  dataset_size_code: highres2d
  dataset_type: 2d_slices
  epochs: 500
  iter_per_epoch: 490
  learning_rate: 7.5e-05
  model_id: unet_3d_slices_residual
  weight_decay: 0

exp_008:
  <<: *exp_007

exp_009:
  <<: *exp_007

...
